/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/control_plane/experimental/v1/seg_detached_extensions.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/control_plane/experimental/v1/seg_detached_extensions.pb-c.h"
void   proto__control_plane__experimental__v1__epicdetached_extension__init
                     (Proto__ControlPlane__Experimental__V1__EPICDetachedExtension         *message)
{
  static const Proto__ControlPlane__Experimental__V1__EPICDetachedExtension init_value = PROTO__CONTROL_PLANE__EXPERIMENTAL__V1__EPICDETACHED_EXTENSION__INIT;
  *message = init_value;
}
size_t proto__control_plane__experimental__v1__epicdetached_extension__get_packed_size
                     (const Proto__ControlPlane__Experimental__V1__EPICDetachedExtension *message)
{
  assert(message->base.descriptor == &proto__control_plane__experimental__v1__epicdetached_extension__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__experimental__v1__epicdetached_extension__pack
                     (const Proto__ControlPlane__Experimental__V1__EPICDetachedExtension *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__experimental__v1__epicdetached_extension__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__experimental__v1__epicdetached_extension__pack_to_buffer
                     (const Proto__ControlPlane__Experimental__V1__EPICDetachedExtension *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__experimental__v1__epicdetached_extension__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__Experimental__V1__EPICDetachedExtension *
       proto__control_plane__experimental__v1__epicdetached_extension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__Experimental__V1__EPICDetachedExtension *)
     protobuf_c_message_unpack (&proto__control_plane__experimental__v1__epicdetached_extension__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__experimental__v1__epicdetached_extension__free_unpacked
                     (Proto__ControlPlane__Experimental__V1__EPICDetachedExtension *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__experimental__v1__epicdetached_extension__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__control_plane__experimental__v1__epicdetached_extension__field_descriptors[2] =
{
  {
    "auth_hop_entry",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__Experimental__V1__EPICDetachedExtension, auth_hop_entry),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auth_peer_entries",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Proto__ControlPlane__Experimental__V1__EPICDetachedExtension, n_auth_peer_entries),
    offsetof(Proto__ControlPlane__Experimental__V1__EPICDetachedExtension, auth_peer_entries),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__experimental__v1__epicdetached_extension__field_indices_by_name[] = {
  0,   /* field[0] = auth_hop_entry */
  1,   /* field[1] = auth_peer_entries */
};
static const ProtobufCIntRange proto__control_plane__experimental__v1__epicdetached_extension__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__experimental__v1__epicdetached_extension__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.experimental.v1.EPICDetachedExtension",
  "EPICDetachedExtension",
  "Proto__ControlPlane__Experimental__V1__EPICDetachedExtension",
  "proto.control_plane.experimental.v1",
  sizeof(Proto__ControlPlane__Experimental__V1__EPICDetachedExtension),
  2,
  proto__control_plane__experimental__v1__epicdetached_extension__field_descriptors,
  proto__control_plane__experimental__v1__epicdetached_extension__field_indices_by_name,
  1,  proto__control_plane__experimental__v1__epicdetached_extension__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__experimental__v1__epicdetached_extension__init,
  NULL,NULL,NULL    /* reserved[123] */
};
