/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/control_plane/experimental/v1/seg_detached_extensions.proto */

#ifndef PROTOBUF_C_proto_2fcontrol_5fplane_2fexperimental_2fv1_2fseg_5fdetached_5fextensions_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fcontrol_5fplane_2fexperimental_2fv1_2fseg_5fdetached_5fextensions_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Proto__ControlPlane__Experimental__V1__EPICDetachedExtension Proto__ControlPlane__Experimental__V1__EPICDetachedExtension;


/* --- enums --- */


/* --- messages --- */

struct  _Proto__ControlPlane__Experimental__V1__EPICDetachedExtension
{
  ProtobufCMessage base;
  /*
   * Remaining bytes of the full MAC in the hop entry.
   */
  ProtobufCBinaryData auth_hop_entry;
  /*
   * Remaining bytes of the full MAC in the peer entries.
   */
  size_t n_auth_peer_entries;
  ProtobufCBinaryData *auth_peer_entries;
};
#define PROTO__CONTROL_PLANE__EXPERIMENTAL__V1__EPICDETACHED_EXTENSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__experimental__v1__epicdetached_extension__descriptor) \
    , {0,NULL}, 0,NULL }


/* Proto__ControlPlane__Experimental__V1__EPICDetachedExtension methods */
void   proto__control_plane__experimental__v1__epicdetached_extension__init
                     (Proto__ControlPlane__Experimental__V1__EPICDetachedExtension         *message);
size_t proto__control_plane__experimental__v1__epicdetached_extension__get_packed_size
                     (const Proto__ControlPlane__Experimental__V1__EPICDetachedExtension   *message);
size_t proto__control_plane__experimental__v1__epicdetached_extension__pack
                     (const Proto__ControlPlane__Experimental__V1__EPICDetachedExtension   *message,
                      uint8_t             *out);
size_t proto__control_plane__experimental__v1__epicdetached_extension__pack_to_buffer
                     (const Proto__ControlPlane__Experimental__V1__EPICDetachedExtension   *message,
                      ProtobufCBuffer     *buffer);
Proto__ControlPlane__Experimental__V1__EPICDetachedExtension *
       proto__control_plane__experimental__v1__epicdetached_extension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__control_plane__experimental__v1__epicdetached_extension__free_unpacked
                     (Proto__ControlPlane__Experimental__V1__EPICDetachedExtension *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Proto__ControlPlane__Experimental__V1__EPICDetachedExtension_Closure)
                 (const Proto__ControlPlane__Experimental__V1__EPICDetachedExtension *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto__control_plane__experimental__v1__epicdetached_extension__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fcontrol_5fplane_2fexperimental_2fv1_2fseg_5fdetached_5fextensions_2eproto__INCLUDED */
