/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/crypto/v1/signed.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "scion/proto/crypto/v1/signed.pb-c.h"
void   proto__crypto__v1__signed_message__init
                     (Proto__Crypto__V1__SignedMessage         *message)
{
  static const Proto__Crypto__V1__SignedMessage init_value = PROTO__CRYPTO__V1__SIGNED_MESSAGE__INIT;
  *message = init_value;
}
size_t proto__crypto__v1__signed_message__get_packed_size
                     (const Proto__Crypto__V1__SignedMessage *message)
{
  assert(message->base.descriptor == &proto__crypto__v1__signed_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__crypto__v1__signed_message__pack
                     (const Proto__Crypto__V1__SignedMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__crypto__v1__signed_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__crypto__v1__signed_message__pack_to_buffer
                     (const Proto__Crypto__V1__SignedMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__crypto__v1__signed_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__Crypto__V1__SignedMessage *
       proto__crypto__v1__signed_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__Crypto__V1__SignedMessage *)
     protobuf_c_message_unpack (&proto__crypto__v1__signed_message__descriptor,
                                allocator, len, data);
}
void   proto__crypto__v1__signed_message__free_unpacked
                     (Proto__Crypto__V1__SignedMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__crypto__v1__signed_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__crypto__v1__header__init
                     (Proto__Crypto__V1__Header         *message)
{
  static const Proto__Crypto__V1__Header init_value = PROTO__CRYPTO__V1__HEADER__INIT;
  *message = init_value;
}
size_t proto__crypto__v1__header__get_packed_size
                     (const Proto__Crypto__V1__Header *message)
{
  assert(message->base.descriptor == &proto__crypto__v1__header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__crypto__v1__header__pack
                     (const Proto__Crypto__V1__Header *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__crypto__v1__header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__crypto__v1__header__pack_to_buffer
                     (const Proto__Crypto__V1__Header *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__crypto__v1__header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__Crypto__V1__Header *
       proto__crypto__v1__header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__Crypto__V1__Header *)
     protobuf_c_message_unpack (&proto__crypto__v1__header__descriptor,
                                allocator, len, data);
}
void   proto__crypto__v1__header__free_unpacked
                     (Proto__Crypto__V1__Header *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__crypto__v1__header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__crypto__v1__header_and_body_internal__init
                     (Proto__Crypto__V1__HeaderAndBodyInternal         *message)
{
  static const Proto__Crypto__V1__HeaderAndBodyInternal init_value = PROTO__CRYPTO__V1__HEADER_AND_BODY_INTERNAL__INIT;
  *message = init_value;
}
size_t proto__crypto__v1__header_and_body_internal__get_packed_size
                     (const Proto__Crypto__V1__HeaderAndBodyInternal *message)
{
  assert(message->base.descriptor == &proto__crypto__v1__header_and_body_internal__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__crypto__v1__header_and_body_internal__pack
                     (const Proto__Crypto__V1__HeaderAndBodyInternal *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__crypto__v1__header_and_body_internal__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__crypto__v1__header_and_body_internal__pack_to_buffer
                     (const Proto__Crypto__V1__HeaderAndBodyInternal *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__crypto__v1__header_and_body_internal__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__Crypto__V1__HeaderAndBodyInternal *
       proto__crypto__v1__header_and_body_internal__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__Crypto__V1__HeaderAndBodyInternal *)
     protobuf_c_message_unpack (&proto__crypto__v1__header_and_body_internal__descriptor,
                                allocator, len, data);
}
void   proto__crypto__v1__header_and_body_internal__free_unpacked
                     (Proto__Crypto__V1__HeaderAndBodyInternal *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__crypto__v1__header_and_body_internal__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__crypto__v1__signed_message__field_descriptors[2] =
{
  {
    "header_and_body",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__Crypto__V1__SignedMessage, header_and_body),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__Crypto__V1__SignedMessage, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__crypto__v1__signed_message__field_indices_by_name[] = {
  0,   /* field[0] = header_and_body */
  1,   /* field[1] = signature */
};
static const ProtobufCIntRange proto__crypto__v1__signed_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__crypto__v1__signed_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.crypto.v1.SignedMessage",
  "SignedMessage",
  "Proto__Crypto__V1__SignedMessage",
  "proto.crypto.v1",
  sizeof(Proto__Crypto__V1__SignedMessage),
  2,
  proto__crypto__v1__signed_message__field_descriptors,
  proto__crypto__v1__signed_message__field_indices_by_name,
  1,  proto__crypto__v1__signed_message__number_ranges,
  (ProtobufCMessageInit) proto__crypto__v1__signed_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__crypto__v1__header__field_descriptors[5] =
{
  {
    "signature_algorithm",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Proto__Crypto__V1__Header, signature_algorithm),
    &proto__crypto__v1__signature_algorithm__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "verification_key_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__Crypto__V1__Header, verification_key_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__Crypto__V1__Header, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__Crypto__V1__Header, metadata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "associated_data_length",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Proto__Crypto__V1__Header, associated_data_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__crypto__v1__header__field_indices_by_name[] = {
  4,   /* field[4] = associated_data_length */
  3,   /* field[3] = metadata */
  0,   /* field[0] = signature_algorithm */
  2,   /* field[2] = timestamp */
  1,   /* field[1] = verification_key_id */
};
static const ProtobufCIntRange proto__crypto__v1__header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor proto__crypto__v1__header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.crypto.v1.Header",
  "Header",
  "Proto__Crypto__V1__Header",
  "proto.crypto.v1",
  sizeof(Proto__Crypto__V1__Header),
  5,
  proto__crypto__v1__header__field_descriptors,
  proto__crypto__v1__header__field_indices_by_name,
  1,  proto__crypto__v1__header__number_ranges,
  (ProtobufCMessageInit) proto__crypto__v1__header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__crypto__v1__header_and_body_internal__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__Crypto__V1__HeaderAndBodyInternal, header),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__Crypto__V1__HeaderAndBodyInternal, body),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__crypto__v1__header_and_body_internal__field_indices_by_name[] = {
  1,   /* field[1] = body */
  0,   /* field[0] = header */
};
static const ProtobufCIntRange proto__crypto__v1__header_and_body_internal__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__crypto__v1__header_and_body_internal__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.crypto.v1.HeaderAndBodyInternal",
  "HeaderAndBodyInternal",
  "Proto__Crypto__V1__HeaderAndBodyInternal",
  "proto.crypto.v1",
  sizeof(Proto__Crypto__V1__HeaderAndBodyInternal),
  2,
  proto__crypto__v1__header_and_body_internal__field_descriptors,
  proto__crypto__v1__header_and_body_internal__field_indices_by_name,
  1,  proto__crypto__v1__header_and_body_internal__number_ranges,
  (ProtobufCMessageInit) proto__crypto__v1__header_and_body_internal__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue proto__crypto__v1__signature_algorithm__enum_values_by_number[4] =
{
  { "SIGNATURE_ALGORITHM_UNSPECIFIED", "PROTO__CRYPTO__V1__SIGNATURE_ALGORITHM__SIGNATURE_ALGORITHM_UNSPECIFIED", 0 },
  { "SIGNATURE_ALGORITHM_ECDSA_WITH_SHA256", "PROTO__CRYPTO__V1__SIGNATURE_ALGORITHM__SIGNATURE_ALGORITHM_ECDSA_WITH_SHA256", 1 },
  { "SIGNATURE_ALGORITHM_ECDSA_WITH_SHA384", "PROTO__CRYPTO__V1__SIGNATURE_ALGORITHM__SIGNATURE_ALGORITHM_ECDSA_WITH_SHA384", 2 },
  { "SIGNATURE_ALGORITHM_ECDSA_WITH_SHA512", "PROTO__CRYPTO__V1__SIGNATURE_ALGORITHM__SIGNATURE_ALGORITHM_ECDSA_WITH_SHA512", 3 },
};
static const ProtobufCIntRange proto__crypto__v1__signature_algorithm__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex proto__crypto__v1__signature_algorithm__enum_values_by_name[4] =
{
  { "SIGNATURE_ALGORITHM_ECDSA_WITH_SHA256", 1 },
  { "SIGNATURE_ALGORITHM_ECDSA_WITH_SHA384", 2 },
  { "SIGNATURE_ALGORITHM_ECDSA_WITH_SHA512", 3 },
  { "SIGNATURE_ALGORITHM_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor proto__crypto__v1__signature_algorithm__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "proto.crypto.v1.SignatureAlgorithm",
  "SignatureAlgorithm",
  "Proto__Crypto__V1__SignatureAlgorithm",
  "proto.crypto.v1",
  4,
  proto__crypto__v1__signature_algorithm__enum_values_by_number,
  4,
  proto__crypto__v1__signature_algorithm__enum_values_by_name,
  1,
  proto__crypto__v1__signature_algorithm__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
