/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/control_plane/v1/seg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/control_plane/v1/seg.pb-c.h"
void   proto__control_plane__v1__segments_request__init
                     (Proto__ControlPlane__V1__SegmentsRequest         *message)
{
  static const Proto__ControlPlane__V1__SegmentsRequest init_value = PROTO__CONTROL_PLANE__V1__SEGMENTS_REQUEST__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__segments_request__get_packed_size
                     (const Proto__ControlPlane__V1__SegmentsRequest *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segments_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__segments_request__pack
                     (const Proto__ControlPlane__V1__SegmentsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segments_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__segments_request__pack_to_buffer
                     (const Proto__ControlPlane__V1__SegmentsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segments_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__SegmentsRequest *
       proto__control_plane__v1__segments_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__SegmentsRequest *)
     protobuf_c_message_unpack (&proto__control_plane__v1__segments_request__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__segments_request__free_unpacked
                     (Proto__ControlPlane__V1__SegmentsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__segments_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__segments_response__segments__init
                     (Proto__ControlPlane__V1__SegmentsResponse__Segments         *message)
{
  static const Proto__ControlPlane__V1__SegmentsResponse__Segments init_value = PROTO__CONTROL_PLANE__V1__SEGMENTS_RESPONSE__SEGMENTS__INIT;
  *message = init_value;
}
void   proto__control_plane__v1__segments_response__segments_entry__init
                     (Proto__ControlPlane__V1__SegmentsResponse__SegmentsEntry         *message)
{
  static const Proto__ControlPlane__V1__SegmentsResponse__SegmentsEntry init_value = PROTO__CONTROL_PLANE__V1__SEGMENTS_RESPONSE__SEGMENTS_ENTRY__INIT;
  *message = init_value;
}
void   proto__control_plane__v1__segments_response__init
                     (Proto__ControlPlane__V1__SegmentsResponse         *message)
{
  static const Proto__ControlPlane__V1__SegmentsResponse init_value = PROTO__CONTROL_PLANE__V1__SEGMENTS_RESPONSE__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__segments_response__get_packed_size
                     (const Proto__ControlPlane__V1__SegmentsResponse *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segments_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__segments_response__pack
                     (const Proto__ControlPlane__V1__SegmentsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segments_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__segments_response__pack_to_buffer
                     (const Proto__ControlPlane__V1__SegmentsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segments_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__SegmentsResponse *
       proto__control_plane__v1__segments_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__SegmentsResponse *)
     protobuf_c_message_unpack (&proto__control_plane__v1__segments_response__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__segments_response__free_unpacked
                     (Proto__ControlPlane__V1__SegmentsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__segments_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__segments_registration_request__segments__init
                     (Proto__ControlPlane__V1__SegmentsRegistrationRequest__Segments         *message)
{
  static const Proto__ControlPlane__V1__SegmentsRegistrationRequest__Segments init_value = PROTO__CONTROL_PLANE__V1__SEGMENTS_REGISTRATION_REQUEST__SEGMENTS__INIT;
  *message = init_value;
}
void   proto__control_plane__v1__segments_registration_request__segments_entry__init
                     (Proto__ControlPlane__V1__SegmentsRegistrationRequest__SegmentsEntry         *message)
{
  static const Proto__ControlPlane__V1__SegmentsRegistrationRequest__SegmentsEntry init_value = PROTO__CONTROL_PLANE__V1__SEGMENTS_REGISTRATION_REQUEST__SEGMENTS_ENTRY__INIT;
  *message = init_value;
}
void   proto__control_plane__v1__segments_registration_request__init
                     (Proto__ControlPlane__V1__SegmentsRegistrationRequest         *message)
{
  static const Proto__ControlPlane__V1__SegmentsRegistrationRequest init_value = PROTO__CONTROL_PLANE__V1__SEGMENTS_REGISTRATION_REQUEST__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__segments_registration_request__get_packed_size
                     (const Proto__ControlPlane__V1__SegmentsRegistrationRequest *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segments_registration_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__segments_registration_request__pack
                     (const Proto__ControlPlane__V1__SegmentsRegistrationRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segments_registration_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__segments_registration_request__pack_to_buffer
                     (const Proto__ControlPlane__V1__SegmentsRegistrationRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segments_registration_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__SegmentsRegistrationRequest *
       proto__control_plane__v1__segments_registration_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__SegmentsRegistrationRequest *)
     protobuf_c_message_unpack (&proto__control_plane__v1__segments_registration_request__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__segments_registration_request__free_unpacked
                     (Proto__ControlPlane__V1__SegmentsRegistrationRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__segments_registration_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__segments_registration_response__init
                     (Proto__ControlPlane__V1__SegmentsRegistrationResponse         *message)
{
  static const Proto__ControlPlane__V1__SegmentsRegistrationResponse init_value = PROTO__CONTROL_PLANE__V1__SEGMENTS_REGISTRATION_RESPONSE__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__segments_registration_response__get_packed_size
                     (const Proto__ControlPlane__V1__SegmentsRegistrationResponse *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segments_registration_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__segments_registration_response__pack
                     (const Proto__ControlPlane__V1__SegmentsRegistrationResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segments_registration_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__segments_registration_response__pack_to_buffer
                     (const Proto__ControlPlane__V1__SegmentsRegistrationResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segments_registration_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__SegmentsRegistrationResponse *
       proto__control_plane__v1__segments_registration_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__SegmentsRegistrationResponse *)
     protobuf_c_message_unpack (&proto__control_plane__v1__segments_registration_response__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__segments_registration_response__free_unpacked
                     (Proto__ControlPlane__V1__SegmentsRegistrationResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__segments_registration_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__beacon_request__init
                     (Proto__ControlPlane__V1__BeaconRequest         *message)
{
  static const Proto__ControlPlane__V1__BeaconRequest init_value = PROTO__CONTROL_PLANE__V1__BEACON_REQUEST__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__beacon_request__get_packed_size
                     (const Proto__ControlPlane__V1__BeaconRequest *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__beacon_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__beacon_request__pack
                     (const Proto__ControlPlane__V1__BeaconRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__beacon_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__beacon_request__pack_to_buffer
                     (const Proto__ControlPlane__V1__BeaconRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__beacon_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__BeaconRequest *
       proto__control_plane__v1__beacon_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__BeaconRequest *)
     protobuf_c_message_unpack (&proto__control_plane__v1__beacon_request__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__beacon_request__free_unpacked
                     (Proto__ControlPlane__V1__BeaconRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__beacon_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__beacon_response__init
                     (Proto__ControlPlane__V1__BeaconResponse         *message)
{
  static const Proto__ControlPlane__V1__BeaconResponse init_value = PROTO__CONTROL_PLANE__V1__BEACON_RESPONSE__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__beacon_response__get_packed_size
                     (const Proto__ControlPlane__V1__BeaconResponse *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__beacon_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__beacon_response__pack
                     (const Proto__ControlPlane__V1__BeaconResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__beacon_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__beacon_response__pack_to_buffer
                     (const Proto__ControlPlane__V1__BeaconResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__beacon_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__BeaconResponse *
       proto__control_plane__v1__beacon_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__BeaconResponse *)
     protobuf_c_message_unpack (&proto__control_plane__v1__beacon_response__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__beacon_response__free_unpacked
                     (Proto__ControlPlane__V1__BeaconResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__beacon_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__path_segment__init
                     (Proto__ControlPlane__V1__PathSegment         *message)
{
  static const Proto__ControlPlane__V1__PathSegment init_value = PROTO__CONTROL_PLANE__V1__PATH_SEGMENT__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__path_segment__get_packed_size
                     (const Proto__ControlPlane__V1__PathSegment *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__path_segment__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__path_segment__pack
                     (const Proto__ControlPlane__V1__PathSegment *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__path_segment__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__path_segment__pack_to_buffer
                     (const Proto__ControlPlane__V1__PathSegment *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__path_segment__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__PathSegment *
       proto__control_plane__v1__path_segment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__PathSegment *)
     protobuf_c_message_unpack (&proto__control_plane__v1__path_segment__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__path_segment__free_unpacked
                     (Proto__ControlPlane__V1__PathSegment *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__path_segment__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__segment_information__init
                     (Proto__ControlPlane__V1__SegmentInformation         *message)
{
  static const Proto__ControlPlane__V1__SegmentInformation init_value = PROTO__CONTROL_PLANE__V1__SEGMENT_INFORMATION__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__segment_information__get_packed_size
                     (const Proto__ControlPlane__V1__SegmentInformation *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segment_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__segment_information__pack
                     (const Proto__ControlPlane__V1__SegmentInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segment_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__segment_information__pack_to_buffer
                     (const Proto__ControlPlane__V1__SegmentInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__segment_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__SegmentInformation *
       proto__control_plane__v1__segment_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__SegmentInformation *)
     protobuf_c_message_unpack (&proto__control_plane__v1__segment_information__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__segment_information__free_unpacked
                     (Proto__ControlPlane__V1__SegmentInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__segment_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__asentry__init
                     (Proto__ControlPlane__V1__ASEntry         *message)
{
  static const Proto__ControlPlane__V1__ASEntry init_value = PROTO__CONTROL_PLANE__V1__ASENTRY__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__asentry__get_packed_size
                     (const Proto__ControlPlane__V1__ASEntry *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__asentry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__asentry__pack
                     (const Proto__ControlPlane__V1__ASEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__asentry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__asentry__pack_to_buffer
                     (const Proto__ControlPlane__V1__ASEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__asentry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__ASEntry *
       proto__control_plane__v1__asentry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__ASEntry *)
     protobuf_c_message_unpack (&proto__control_plane__v1__asentry__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__asentry__free_unpacked
                     (Proto__ControlPlane__V1__ASEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__asentry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__asentry_signed_body__init
                     (Proto__ControlPlane__V1__ASEntrySignedBody         *message)
{
  static const Proto__ControlPlane__V1__ASEntrySignedBody init_value = PROTO__CONTROL_PLANE__V1__ASENTRY_SIGNED_BODY__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__asentry_signed_body__get_packed_size
                     (const Proto__ControlPlane__V1__ASEntrySignedBody *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__asentry_signed_body__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__asentry_signed_body__pack
                     (const Proto__ControlPlane__V1__ASEntrySignedBody *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__asentry_signed_body__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__asentry_signed_body__pack_to_buffer
                     (const Proto__ControlPlane__V1__ASEntrySignedBody *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__asentry_signed_body__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__ASEntrySignedBody *
       proto__control_plane__v1__asentry_signed_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__ASEntrySignedBody *)
     protobuf_c_message_unpack (&proto__control_plane__v1__asentry_signed_body__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__asentry_signed_body__free_unpacked
                     (Proto__ControlPlane__V1__ASEntrySignedBody *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__asentry_signed_body__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__hop_entry__init
                     (Proto__ControlPlane__V1__HopEntry         *message)
{
  static const Proto__ControlPlane__V1__HopEntry init_value = PROTO__CONTROL_PLANE__V1__HOP_ENTRY__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__hop_entry__get_packed_size
                     (const Proto__ControlPlane__V1__HopEntry *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__hop_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__hop_entry__pack
                     (const Proto__ControlPlane__V1__HopEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__hop_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__hop_entry__pack_to_buffer
                     (const Proto__ControlPlane__V1__HopEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__hop_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__HopEntry *
       proto__control_plane__v1__hop_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__HopEntry *)
     protobuf_c_message_unpack (&proto__control_plane__v1__hop_entry__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__hop_entry__free_unpacked
                     (Proto__ControlPlane__V1__HopEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__hop_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__peer_entry__init
                     (Proto__ControlPlane__V1__PeerEntry         *message)
{
  static const Proto__ControlPlane__V1__PeerEntry init_value = PROTO__CONTROL_PLANE__V1__PEER_ENTRY__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__peer_entry__get_packed_size
                     (const Proto__ControlPlane__V1__PeerEntry *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__peer_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__peer_entry__pack
                     (const Proto__ControlPlane__V1__PeerEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__peer_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__peer_entry__pack_to_buffer
                     (const Proto__ControlPlane__V1__PeerEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__peer_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__PeerEntry *
       proto__control_plane__v1__peer_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__PeerEntry *)
     protobuf_c_message_unpack (&proto__control_plane__v1__peer_entry__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__peer_entry__free_unpacked
                     (Proto__ControlPlane__V1__PeerEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__peer_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__hop_field__init
                     (Proto__ControlPlane__V1__HopField         *message)
{
  static const Proto__ControlPlane__V1__HopField init_value = PROTO__CONTROL_PLANE__V1__HOP_FIELD__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__hop_field__get_packed_size
                     (const Proto__ControlPlane__V1__HopField *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__hop_field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__hop_field__pack
                     (const Proto__ControlPlane__V1__HopField *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__hop_field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__hop_field__pack_to_buffer
                     (const Proto__ControlPlane__V1__HopField *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__hop_field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__HopField *
       proto__control_plane__v1__hop_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__HopField *)
     protobuf_c_message_unpack (&proto__control_plane__v1__hop_field__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__hop_field__free_unpacked
                     (Proto__ControlPlane__V1__HopField *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__hop_field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__control_plane__v1__segments_request__field_descriptors[2] =
{
  {
    "src_isd_as",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__SegmentsRequest, src_isd_as),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_isd_as",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__SegmentsRequest, dst_isd_as),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__segments_request__field_indices_by_name[] = {
  1,   /* field[1] = dst_isd_as */
  0,   /* field[0] = src_isd_as */
};
static const ProtobufCIntRange proto__control_plane__v1__segments_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__segments_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.SegmentsRequest",
  "SegmentsRequest",
  "Proto__ControlPlane__V1__SegmentsRequest",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__SegmentsRequest),
  2,
  proto__control_plane__v1__segments_request__field_descriptors,
  proto__control_plane__v1__segments_request__field_indices_by_name,
  1,  proto__control_plane__v1__segments_request__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__segments_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__segments_response__segments__field_descriptors[1] =
{
  {
    "segments",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ControlPlane__V1__SegmentsResponse__Segments, n_segments),
    offsetof(Proto__ControlPlane__V1__SegmentsResponse__Segments, segments),
    &proto__control_plane__v1__path_segment__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__segments_response__segments__field_indices_by_name[] = {
  0,   /* field[0] = segments */
};
static const ProtobufCIntRange proto__control_plane__v1__segments_response__segments__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__segments_response__segments__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.SegmentsResponse.Segments",
  "Segments",
  "Proto__ControlPlane__V1__SegmentsResponse__Segments",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__SegmentsResponse__Segments),
  1,
  proto__control_plane__v1__segments_response__segments__field_descriptors,
  proto__control_plane__v1__segments_response__segments__field_indices_by_name,
  1,  proto__control_plane__v1__segments_response__segments__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__segments_response__segments__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__segments_response__segments_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__SegmentsResponse__SegmentsEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__SegmentsResponse__SegmentsEntry, value),
    &proto__control_plane__v1__segments_response__segments__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__segments_response__segments_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange proto__control_plane__v1__segments_response__segments_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__segments_response__segments_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.SegmentsResponse.SegmentsEntry",
  "SegmentsEntry",
  "Proto__ControlPlane__V1__SegmentsResponse__SegmentsEntry",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__SegmentsResponse__SegmentsEntry),
  2,
  proto__control_plane__v1__segments_response__segments_entry__field_descriptors,
  proto__control_plane__v1__segments_response__segments_entry__field_indices_by_name,
  1,  proto__control_plane__v1__segments_response__segments_entry__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__segments_response__segments_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__segments_response__field_descriptors[2] =
{
  {
    "segments",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ControlPlane__V1__SegmentsResponse, n_segments),
    offsetof(Proto__ControlPlane__V1__SegmentsResponse, segments),
    &proto__control_plane__v1__segments_response__segments_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deprecated_signed_revocations",
    1000,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Proto__ControlPlane__V1__SegmentsResponse, n_deprecated_signed_revocations),
    offsetof(Proto__ControlPlane__V1__SegmentsResponse, deprecated_signed_revocations),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__segments_response__field_indices_by_name[] = {
  1,   /* field[1] = deprecated_signed_revocations */
  0,   /* field[0] = segments */
};
static const ProtobufCIntRange proto__control_plane__v1__segments_response__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 1000, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__segments_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.SegmentsResponse",
  "SegmentsResponse",
  "Proto__ControlPlane__V1__SegmentsResponse",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__SegmentsResponse),
  2,
  proto__control_plane__v1__segments_response__field_descriptors,
  proto__control_plane__v1__segments_response__field_indices_by_name,
  2,  proto__control_plane__v1__segments_response__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__segments_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__segments_registration_request__segments__field_descriptors[1] =
{
  {
    "segments",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ControlPlane__V1__SegmentsRegistrationRequest__Segments, n_segments),
    offsetof(Proto__ControlPlane__V1__SegmentsRegistrationRequest__Segments, segments),
    &proto__control_plane__v1__path_segment__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__segments_registration_request__segments__field_indices_by_name[] = {
  0,   /* field[0] = segments */
};
static const ProtobufCIntRange proto__control_plane__v1__segments_registration_request__segments__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__segments_registration_request__segments__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.SegmentsRegistrationRequest.Segments",
  "Segments",
  "Proto__ControlPlane__V1__SegmentsRegistrationRequest__Segments",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__SegmentsRegistrationRequest__Segments),
  1,
  proto__control_plane__v1__segments_registration_request__segments__field_descriptors,
  proto__control_plane__v1__segments_registration_request__segments__field_indices_by_name,
  1,  proto__control_plane__v1__segments_registration_request__segments__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__segments_registration_request__segments__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__segments_registration_request__segments_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__SegmentsRegistrationRequest__SegmentsEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__SegmentsRegistrationRequest__SegmentsEntry, value),
    &proto__control_plane__v1__segments_registration_request__segments__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__segments_registration_request__segments_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange proto__control_plane__v1__segments_registration_request__segments_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__segments_registration_request__segments_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.SegmentsRegistrationRequest.SegmentsEntry",
  "SegmentsEntry",
  "Proto__ControlPlane__V1__SegmentsRegistrationRequest__SegmentsEntry",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__SegmentsRegistrationRequest__SegmentsEntry),
  2,
  proto__control_plane__v1__segments_registration_request__segments_entry__field_descriptors,
  proto__control_plane__v1__segments_registration_request__segments_entry__field_indices_by_name,
  1,  proto__control_plane__v1__segments_registration_request__segments_entry__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__segments_registration_request__segments_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__segments_registration_request__field_descriptors[1] =
{
  {
    "segments",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ControlPlane__V1__SegmentsRegistrationRequest, n_segments),
    offsetof(Proto__ControlPlane__V1__SegmentsRegistrationRequest, segments),
    &proto__control_plane__v1__segments_registration_request__segments_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__segments_registration_request__field_indices_by_name[] = {
  0,   /* field[0] = segments */
};
static const ProtobufCIntRange proto__control_plane__v1__segments_registration_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__segments_registration_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.SegmentsRegistrationRequest",
  "SegmentsRegistrationRequest",
  "Proto__ControlPlane__V1__SegmentsRegistrationRequest",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__SegmentsRegistrationRequest),
  1,
  proto__control_plane__v1__segments_registration_request__field_descriptors,
  proto__control_plane__v1__segments_registration_request__field_indices_by_name,
  1,  proto__control_plane__v1__segments_registration_request__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__segments_registration_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define proto__control_plane__v1__segments_registration_response__field_descriptors NULL
#define proto__control_plane__v1__segments_registration_response__field_indices_by_name NULL
#define proto__control_plane__v1__segments_registration_response__number_ranges NULL
const ProtobufCMessageDescriptor proto__control_plane__v1__segments_registration_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.SegmentsRegistrationResponse",
  "SegmentsRegistrationResponse",
  "Proto__ControlPlane__V1__SegmentsRegistrationResponse",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__SegmentsRegistrationResponse),
  0,
  proto__control_plane__v1__segments_registration_response__field_descriptors,
  proto__control_plane__v1__segments_registration_response__field_indices_by_name,
  0,  proto__control_plane__v1__segments_registration_response__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__segments_registration_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__beacon_request__field_descriptors[1] =
{
  {
    "segment",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__BeaconRequest, segment),
    &proto__control_plane__v1__path_segment__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__beacon_request__field_indices_by_name[] = {
  0,   /* field[0] = segment */
};
static const ProtobufCIntRange proto__control_plane__v1__beacon_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__beacon_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.BeaconRequest",
  "BeaconRequest",
  "Proto__ControlPlane__V1__BeaconRequest",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__BeaconRequest),
  1,
  proto__control_plane__v1__beacon_request__field_descriptors,
  proto__control_plane__v1__beacon_request__field_indices_by_name,
  1,  proto__control_plane__v1__beacon_request__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__beacon_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define proto__control_plane__v1__beacon_response__field_descriptors NULL
#define proto__control_plane__v1__beacon_response__field_indices_by_name NULL
#define proto__control_plane__v1__beacon_response__number_ranges NULL
const ProtobufCMessageDescriptor proto__control_plane__v1__beacon_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.BeaconResponse",
  "BeaconResponse",
  "Proto__ControlPlane__V1__BeaconResponse",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__BeaconResponse),
  0,
  proto__control_plane__v1__beacon_response__field_descriptors,
  proto__control_plane__v1__beacon_response__field_indices_by_name,
  0,  proto__control_plane__v1__beacon_response__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__beacon_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__path_segment__field_descriptors[2] =
{
  {
    "segment_info",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__PathSegment, segment_info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "as_entries",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ControlPlane__V1__PathSegment, n_as_entries),
    offsetof(Proto__ControlPlane__V1__PathSegment, as_entries),
    &proto__control_plane__v1__asentry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__path_segment__field_indices_by_name[] = {
  1,   /* field[1] = as_entries */
  0,   /* field[0] = segment_info */
};
static const ProtobufCIntRange proto__control_plane__v1__path_segment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__path_segment__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.PathSegment",
  "PathSegment",
  "Proto__ControlPlane__V1__PathSegment",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__PathSegment),
  2,
  proto__control_plane__v1__path_segment__field_descriptors,
  proto__control_plane__v1__path_segment__field_indices_by_name,
  1,  proto__control_plane__v1__path_segment__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__path_segment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__segment_information__field_descriptors[2] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__SegmentInformation, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "segment_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__SegmentInformation, segment_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__segment_information__field_indices_by_name[] = {
  1,   /* field[1] = segment_id */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange proto__control_plane__v1__segment_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__segment_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.SegmentInformation",
  "SegmentInformation",
  "Proto__ControlPlane__V1__SegmentInformation",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__SegmentInformation),
  2,
  proto__control_plane__v1__segment_information__field_descriptors,
  proto__control_plane__v1__segment_information__field_indices_by_name,
  1,  proto__control_plane__v1__segment_information__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__segment_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__asentry__field_descriptors[2] =
{
  {
    "signed",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__ASEntry, signed_),
    &proto__crypto__v1__signed_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unsigned",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__ASEntry, unsigned_),
    &proto__control_plane__v1__path_segment_unsigned_extensions__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__asentry__field_indices_by_name[] = {
  0,   /* field[0] = signed */
  1,   /* field[1] = unsigned */
};
static const ProtobufCIntRange proto__control_plane__v1__asentry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__asentry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.ASEntry",
  "ASEntry",
  "Proto__ControlPlane__V1__ASEntry",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__ASEntry),
  2,
  proto__control_plane__v1__asentry__field_descriptors,
  proto__control_plane__v1__asentry__field_indices_by_name,
  1,  proto__control_plane__v1__asentry__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__asentry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__asentry_signed_body__field_descriptors[6] =
{
  {
    "isd_as",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__ASEntrySignedBody, isd_as),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next_isd_as",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__ASEntrySignedBody, next_isd_as),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hop_entry",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__ASEntrySignedBody, hop_entry),
    &proto__control_plane__v1__hop_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peer_entries",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ControlPlane__V1__ASEntrySignedBody, n_peer_entries),
    offsetof(Proto__ControlPlane__V1__ASEntrySignedBody, peer_entries),
    &proto__control_plane__v1__peer_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mtu",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__ASEntrySignedBody, mtu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extensions",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__ASEntrySignedBody, extensions),
    &proto__control_plane__v1__path_segment_extensions__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__asentry_signed_body__field_indices_by_name[] = {
  5,   /* field[5] = extensions */
  2,   /* field[2] = hop_entry */
  0,   /* field[0] = isd_as */
  4,   /* field[4] = mtu */
  1,   /* field[1] = next_isd_as */
  3,   /* field[3] = peer_entries */
};
static const ProtobufCIntRange proto__control_plane__v1__asentry_signed_body__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__asentry_signed_body__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.ASEntrySignedBody",
  "ASEntrySignedBody",
  "Proto__ControlPlane__V1__ASEntrySignedBody",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__ASEntrySignedBody),
  6,
  proto__control_plane__v1__asentry_signed_body__field_descriptors,
  proto__control_plane__v1__asentry_signed_body__field_indices_by_name,
  1,  proto__control_plane__v1__asentry_signed_body__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__asentry_signed_body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__hop_entry__field_descriptors[2] =
{
  {
    "hop_field",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__HopEntry, hop_field),
    &proto__control_plane__v1__hop_field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ingress_mtu",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__HopEntry, ingress_mtu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__hop_entry__field_indices_by_name[] = {
  0,   /* field[0] = hop_field */
  1,   /* field[1] = ingress_mtu */
};
static const ProtobufCIntRange proto__control_plane__v1__hop_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__hop_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.HopEntry",
  "HopEntry",
  "Proto__ControlPlane__V1__HopEntry",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__HopEntry),
  2,
  proto__control_plane__v1__hop_entry__field_descriptors,
  proto__control_plane__v1__hop_entry__field_indices_by_name,
  1,  proto__control_plane__v1__hop_entry__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__hop_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__peer_entry__field_descriptors[4] =
{
  {
    "peer_isd_as",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__PeerEntry, peer_isd_as),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peer_interface",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__PeerEntry, peer_interface),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peer_mtu",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__PeerEntry, peer_mtu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hop_field",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__PeerEntry, hop_field),
    &proto__control_plane__v1__hop_field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__peer_entry__field_indices_by_name[] = {
  3,   /* field[3] = hop_field */
  1,   /* field[1] = peer_interface */
  0,   /* field[0] = peer_isd_as */
  2,   /* field[2] = peer_mtu */
};
static const ProtobufCIntRange proto__control_plane__v1__peer_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__peer_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.PeerEntry",
  "PeerEntry",
  "Proto__ControlPlane__V1__PeerEntry",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__PeerEntry),
  4,
  proto__control_plane__v1__peer_entry__field_descriptors,
  proto__control_plane__v1__peer_entry__field_indices_by_name,
  1,  proto__control_plane__v1__peer_entry__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__peer_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__hop_field__field_descriptors[4] =
{
  {
    "ingress",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__HopField, ingress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "egress",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__HopField, egress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exp_time",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__HopField, exp_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__HopField, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__hop_field__field_indices_by_name[] = {
  1,   /* field[1] = egress */
  2,   /* field[2] = exp_time */
  0,   /* field[0] = ingress */
  3,   /* field[3] = mac */
};
static const ProtobufCIntRange proto__control_plane__v1__hop_field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__hop_field__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.HopField",
  "HopField",
  "Proto__ControlPlane__V1__HopField",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__HopField),
  4,
  proto__control_plane__v1__hop_field__field_descriptors,
  proto__control_plane__v1__hop_field__field_indices_by_name,
  1,  proto__control_plane__v1__hop_field__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__hop_field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue proto__control_plane__v1__segment_type__enum_values_by_number[4] =
{
  { "SEGMENT_TYPE_UNSPECIFIED", "PROTO__CONTROL_PLANE__V1__SEGMENT_TYPE__SEGMENT_TYPE_UNSPECIFIED", 0 },
  { "SEGMENT_TYPE_UP", "PROTO__CONTROL_PLANE__V1__SEGMENT_TYPE__SEGMENT_TYPE_UP", 1 },
  { "SEGMENT_TYPE_DOWN", "PROTO__CONTROL_PLANE__V1__SEGMENT_TYPE__SEGMENT_TYPE_DOWN", 2 },
  { "SEGMENT_TYPE_CORE", "PROTO__CONTROL_PLANE__V1__SEGMENT_TYPE__SEGMENT_TYPE_CORE", 3 },
};
static const ProtobufCIntRange proto__control_plane__v1__segment_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex proto__control_plane__v1__segment_type__enum_values_by_name[4] =
{
  { "SEGMENT_TYPE_CORE", 3 },
  { "SEGMENT_TYPE_DOWN", 2 },
  { "SEGMENT_TYPE_UNSPECIFIED", 0 },
  { "SEGMENT_TYPE_UP", 1 },
};
const ProtobufCEnumDescriptor proto__control_plane__v1__segment_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.SegmentType",
  "SegmentType",
  "Proto__ControlPlane__V1__SegmentType",
  "proto.control_plane.v1",
  4,
  proto__control_plane__v1__segment_type__enum_values_by_number,
  4,
  proto__control_plane__v1__segment_type__enum_values_by_name,
  1,
  proto__control_plane__v1__segment_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCMethodDescriptor proto__control_plane__v1__segment_lookup_service__method_descriptors[1] =
{
  { "Segments", &proto__control_plane__v1__segments_request__descriptor, &proto__control_plane__v1__segments_response__descriptor },
};
const unsigned proto__control_plane__v1__segment_lookup_service__method_indices_by_name[] = {
  0         /* Segments */
};
const ProtobufCServiceDescriptor proto__control_plane__v1__segment_lookup_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.SegmentLookupService",
  "SegmentLookupService",
  "Proto__ControlPlane__V1__SegmentLookupService",
  "proto.control_plane.v1",
  1,
  proto__control_plane__v1__segment_lookup_service__method_descriptors,
  proto__control_plane__v1__segment_lookup_service__method_indices_by_name
};
void proto__control_plane__v1__segment_lookup_service__segments(ProtobufCService *service,
                                                                const Proto__ControlPlane__V1__SegmentsRequest *input,
                                                                Proto__ControlPlane__V1__SegmentsResponse_Closure closure,
                                                                void *closure_data)
{
  assert(service->descriptor == &proto__control_plane__v1__segment_lookup_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__control_plane__v1__segment_lookup_service__init (Proto__ControlPlane__V1__SegmentLookupService_Service *service,
                                                             Proto__ControlPlane__V1__SegmentLookupService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &proto__control_plane__v1__segment_lookup_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
static const ProtobufCMethodDescriptor proto__control_plane__v1__segment_registration_service__method_descriptors[1] =
{
  { "SegmentsRegistration", &proto__control_plane__v1__segments_registration_request__descriptor, &proto__control_plane__v1__segments_registration_response__descriptor },
};
const unsigned proto__control_plane__v1__segment_registration_service__method_indices_by_name[] = {
  0         /* SegmentsRegistration */
};
const ProtobufCServiceDescriptor proto__control_plane__v1__segment_registration_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.SegmentRegistrationService",
  "SegmentRegistrationService",
  "Proto__ControlPlane__V1__SegmentRegistrationService",
  "proto.control_plane.v1",
  1,
  proto__control_plane__v1__segment_registration_service__method_descriptors,
  proto__control_plane__v1__segment_registration_service__method_indices_by_name
};
void proto__control_plane__v1__segment_registration_service__segments_registration(ProtobufCService *service,
                                                                                   const Proto__ControlPlane__V1__SegmentsRegistrationRequest *input,
                                                                                   Proto__ControlPlane__V1__SegmentsRegistrationResponse_Closure closure,
                                                                                   void *closure_data)
{
  assert(service->descriptor == &proto__control_plane__v1__segment_registration_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__control_plane__v1__segment_registration_service__init (Proto__ControlPlane__V1__SegmentRegistrationService_Service *service,
                                                                   Proto__ControlPlane__V1__SegmentRegistrationService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &proto__control_plane__v1__segment_registration_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
static const ProtobufCMethodDescriptor proto__control_plane__v1__segment_creation_service__method_descriptors[1] =
{
  { "Beacon", &proto__control_plane__v1__beacon_request__descriptor, &proto__control_plane__v1__beacon_response__descriptor },
};
const unsigned proto__control_plane__v1__segment_creation_service__method_indices_by_name[] = {
  0         /* Beacon */
};
const ProtobufCServiceDescriptor proto__control_plane__v1__segment_creation_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.SegmentCreationService",
  "SegmentCreationService",
  "Proto__ControlPlane__V1__SegmentCreationService",
  "proto.control_plane.v1",
  1,
  proto__control_plane__v1__segment_creation_service__method_descriptors,
  proto__control_plane__v1__segment_creation_service__method_indices_by_name
};
void proto__control_plane__v1__segment_creation_service__beacon(ProtobufCService *service,
                                                                const Proto__ControlPlane__V1__BeaconRequest *input,
                                                                Proto__ControlPlane__V1__BeaconResponse_Closure closure,
                                                                void *closure_data)
{
  assert(service->descriptor == &proto__control_plane__v1__segment_creation_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__control_plane__v1__segment_creation_service__init (Proto__ControlPlane__V1__SegmentCreationService_Service *service,
                                                               Proto__ControlPlane__V1__SegmentCreationService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &proto__control_plane__v1__segment_creation_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
