/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/control_plane/v1/seg_extensions.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "scion/proto/control_plane/v1/seg_extensions.pb-c.h"
void   proto__control_plane__v1__path_segment_extensions__init
                     (Proto__ControlPlane__V1__PathSegmentExtensions         *message)
{
  static const Proto__ControlPlane__V1__PathSegmentExtensions init_value = PROTO__CONTROL_PLANE__V1__PATH_SEGMENT_EXTENSIONS__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__path_segment_extensions__get_packed_size
                     (const Proto__ControlPlane__V1__PathSegmentExtensions *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__path_segment_extensions__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__path_segment_extensions__pack
                     (const Proto__ControlPlane__V1__PathSegmentExtensions *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__path_segment_extensions__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__path_segment_extensions__pack_to_buffer
                     (const Proto__ControlPlane__V1__PathSegmentExtensions *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__path_segment_extensions__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__PathSegmentExtensions *
       proto__control_plane__v1__path_segment_extensions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__PathSegmentExtensions *)
     protobuf_c_message_unpack (&proto__control_plane__v1__path_segment_extensions__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__path_segment_extensions__free_unpacked
                     (Proto__ControlPlane__V1__PathSegmentExtensions *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__path_segment_extensions__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__hidden_path_extension__init
                     (Proto__ControlPlane__V1__HiddenPathExtension         *message)
{
  static const Proto__ControlPlane__V1__HiddenPathExtension init_value = PROTO__CONTROL_PLANE__V1__HIDDEN_PATH_EXTENSION__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__hidden_path_extension__get_packed_size
                     (const Proto__ControlPlane__V1__HiddenPathExtension *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__hidden_path_extension__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__hidden_path_extension__pack
                     (const Proto__ControlPlane__V1__HiddenPathExtension *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__hidden_path_extension__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__hidden_path_extension__pack_to_buffer
                     (const Proto__ControlPlane__V1__HiddenPathExtension *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__hidden_path_extension__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__HiddenPathExtension *
       proto__control_plane__v1__hidden_path_extension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__HiddenPathExtension *)
     protobuf_c_message_unpack (&proto__control_plane__v1__hidden_path_extension__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__hidden_path_extension__free_unpacked
                     (Proto__ControlPlane__V1__HiddenPathExtension *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__hidden_path_extension__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__static_info_extension__geo_entry__init
                     (Proto__ControlPlane__V1__StaticInfoExtension__GeoEntry         *message)
{
  static const Proto__ControlPlane__V1__StaticInfoExtension__GeoEntry init_value = PROTO__CONTROL_PLANE__V1__STATIC_INFO_EXTENSION__GEO_ENTRY__INIT;
  *message = init_value;
}
void   proto__control_plane__v1__static_info_extension__link_type_entry__init
                     (Proto__ControlPlane__V1__StaticInfoExtension__LinkTypeEntry         *message)
{
  static const Proto__ControlPlane__V1__StaticInfoExtension__LinkTypeEntry init_value = PROTO__CONTROL_PLANE__V1__STATIC_INFO_EXTENSION__LINK_TYPE_ENTRY__INIT;
  *message = init_value;
}
void   proto__control_plane__v1__static_info_extension__internal_hops_entry__init
                     (Proto__ControlPlane__V1__StaticInfoExtension__InternalHopsEntry         *message)
{
  static const Proto__ControlPlane__V1__StaticInfoExtension__InternalHopsEntry init_value = PROTO__CONTROL_PLANE__V1__STATIC_INFO_EXTENSION__INTERNAL_HOPS_ENTRY__INIT;
  *message = init_value;
}
void   proto__control_plane__v1__static_info_extension__init
                     (Proto__ControlPlane__V1__StaticInfoExtension         *message)
{
  static const Proto__ControlPlane__V1__StaticInfoExtension init_value = PROTO__CONTROL_PLANE__V1__STATIC_INFO_EXTENSION__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__static_info_extension__get_packed_size
                     (const Proto__ControlPlane__V1__StaticInfoExtension *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__static_info_extension__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__static_info_extension__pack
                     (const Proto__ControlPlane__V1__StaticInfoExtension *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__static_info_extension__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__static_info_extension__pack_to_buffer
                     (const Proto__ControlPlane__V1__StaticInfoExtension *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__static_info_extension__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__StaticInfoExtension *
       proto__control_plane__v1__static_info_extension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__StaticInfoExtension *)
     protobuf_c_message_unpack (&proto__control_plane__v1__static_info_extension__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__static_info_extension__free_unpacked
                     (Proto__ControlPlane__V1__StaticInfoExtension *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__static_info_extension__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__latency_info__intra_entry__init
                     (Proto__ControlPlane__V1__LatencyInfo__IntraEntry         *message)
{
  static const Proto__ControlPlane__V1__LatencyInfo__IntraEntry init_value = PROTO__CONTROL_PLANE__V1__LATENCY_INFO__INTRA_ENTRY__INIT;
  *message = init_value;
}
void   proto__control_plane__v1__latency_info__inter_entry__init
                     (Proto__ControlPlane__V1__LatencyInfo__InterEntry         *message)
{
  static const Proto__ControlPlane__V1__LatencyInfo__InterEntry init_value = PROTO__CONTROL_PLANE__V1__LATENCY_INFO__INTER_ENTRY__INIT;
  *message = init_value;
}
void   proto__control_plane__v1__latency_info__init
                     (Proto__ControlPlane__V1__LatencyInfo         *message)
{
  static const Proto__ControlPlane__V1__LatencyInfo init_value = PROTO__CONTROL_PLANE__V1__LATENCY_INFO__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__latency_info__get_packed_size
                     (const Proto__ControlPlane__V1__LatencyInfo *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__latency_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__latency_info__pack
                     (const Proto__ControlPlane__V1__LatencyInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__latency_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__latency_info__pack_to_buffer
                     (const Proto__ControlPlane__V1__LatencyInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__latency_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__LatencyInfo *
       proto__control_plane__v1__latency_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__LatencyInfo *)
     protobuf_c_message_unpack (&proto__control_plane__v1__latency_info__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__latency_info__free_unpacked
                     (Proto__ControlPlane__V1__LatencyInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__latency_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__bandwidth_info__intra_entry__init
                     (Proto__ControlPlane__V1__BandwidthInfo__IntraEntry         *message)
{
  static const Proto__ControlPlane__V1__BandwidthInfo__IntraEntry init_value = PROTO__CONTROL_PLANE__V1__BANDWIDTH_INFO__INTRA_ENTRY__INIT;
  *message = init_value;
}
void   proto__control_plane__v1__bandwidth_info__inter_entry__init
                     (Proto__ControlPlane__V1__BandwidthInfo__InterEntry         *message)
{
  static const Proto__ControlPlane__V1__BandwidthInfo__InterEntry init_value = PROTO__CONTROL_PLANE__V1__BANDWIDTH_INFO__INTER_ENTRY__INIT;
  *message = init_value;
}
void   proto__control_plane__v1__bandwidth_info__init
                     (Proto__ControlPlane__V1__BandwidthInfo         *message)
{
  static const Proto__ControlPlane__V1__BandwidthInfo init_value = PROTO__CONTROL_PLANE__V1__BANDWIDTH_INFO__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__bandwidth_info__get_packed_size
                     (const Proto__ControlPlane__V1__BandwidthInfo *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__bandwidth_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__bandwidth_info__pack
                     (const Proto__ControlPlane__V1__BandwidthInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__bandwidth_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__bandwidth_info__pack_to_buffer
                     (const Proto__ControlPlane__V1__BandwidthInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__bandwidth_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__BandwidthInfo *
       proto__control_plane__v1__bandwidth_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__BandwidthInfo *)
     protobuf_c_message_unpack (&proto__control_plane__v1__bandwidth_info__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__bandwidth_info__free_unpacked
                     (Proto__ControlPlane__V1__BandwidthInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__bandwidth_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__geo_coordinates__init
                     (Proto__ControlPlane__V1__GeoCoordinates         *message)
{
  static const Proto__ControlPlane__V1__GeoCoordinates init_value = PROTO__CONTROL_PLANE__V1__GEO_COORDINATES__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__geo_coordinates__get_packed_size
                     (const Proto__ControlPlane__V1__GeoCoordinates *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__geo_coordinates__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__geo_coordinates__pack
                     (const Proto__ControlPlane__V1__GeoCoordinates *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__geo_coordinates__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__geo_coordinates__pack_to_buffer
                     (const Proto__ControlPlane__V1__GeoCoordinates *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__geo_coordinates__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__GeoCoordinates *
       proto__control_plane__v1__geo_coordinates__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__GeoCoordinates *)
     protobuf_c_message_unpack (&proto__control_plane__v1__geo_coordinates__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__geo_coordinates__free_unpacked
                     (Proto__ControlPlane__V1__GeoCoordinates *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__geo_coordinates__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__digest_extension__digest__init
                     (Proto__ControlPlane__V1__DigestExtension__Digest         *message)
{
  static const Proto__ControlPlane__V1__DigestExtension__Digest init_value = PROTO__CONTROL_PLANE__V1__DIGEST_EXTENSION__DIGEST__INIT;
  *message = init_value;
}
void   proto__control_plane__v1__digest_extension__init
                     (Proto__ControlPlane__V1__DigestExtension         *message)
{
  static const Proto__ControlPlane__V1__DigestExtension init_value = PROTO__CONTROL_PLANE__V1__DIGEST_EXTENSION__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__digest_extension__get_packed_size
                     (const Proto__ControlPlane__V1__DigestExtension *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__digest_extension__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__digest_extension__pack
                     (const Proto__ControlPlane__V1__DigestExtension *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__digest_extension__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__digest_extension__pack_to_buffer
                     (const Proto__ControlPlane__V1__DigestExtension *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__digest_extension__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__DigestExtension *
       proto__control_plane__v1__digest_extension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__DigestExtension *)
     protobuf_c_message_unpack (&proto__control_plane__v1__digest_extension__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__digest_extension__free_unpacked
                     (Proto__ControlPlane__V1__DigestExtension *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__digest_extension__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__control_plane__v1__path_segment_unsigned_extensions__init
                     (Proto__ControlPlane__V1__PathSegmentUnsignedExtensions         *message)
{
  static const Proto__ControlPlane__V1__PathSegmentUnsignedExtensions init_value = PROTO__CONTROL_PLANE__V1__PATH_SEGMENT_UNSIGNED_EXTENSIONS__INIT;
  *message = init_value;
}
size_t proto__control_plane__v1__path_segment_unsigned_extensions__get_packed_size
                     (const Proto__ControlPlane__V1__PathSegmentUnsignedExtensions *message)
{
  assert(message->base.descriptor == &proto__control_plane__v1__path_segment_unsigned_extensions__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__control_plane__v1__path_segment_unsigned_extensions__pack
                     (const Proto__ControlPlane__V1__PathSegmentUnsignedExtensions *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__control_plane__v1__path_segment_unsigned_extensions__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__control_plane__v1__path_segment_unsigned_extensions__pack_to_buffer
                     (const Proto__ControlPlane__V1__PathSegmentUnsignedExtensions *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__control_plane__v1__path_segment_unsigned_extensions__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ControlPlane__V1__PathSegmentUnsignedExtensions *
       proto__control_plane__v1__path_segment_unsigned_extensions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ControlPlane__V1__PathSegmentUnsignedExtensions *)
     protobuf_c_message_unpack (&proto__control_plane__v1__path_segment_unsigned_extensions__descriptor,
                                allocator, len, data);
}
void   proto__control_plane__v1__path_segment_unsigned_extensions__free_unpacked
                     (Proto__ControlPlane__V1__PathSegmentUnsignedExtensions *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__control_plane__v1__path_segment_unsigned_extensions__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__control_plane__v1__path_segment_extensions__field_descriptors[3] =
{
  {
    "static_info",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__PathSegmentExtensions, static_info),
    &proto__control_plane__v1__static_info_extension__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hidden_path",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__PathSegmentExtensions, hidden_path),
    &proto__control_plane__v1__hidden_path_extension__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "digests",
    1000,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__PathSegmentExtensions, digests),
    &proto__control_plane__v1__digest_extension__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__path_segment_extensions__field_indices_by_name[] = {
  2,   /* field[2] = digests */
  1,   /* field[1] = hidden_path */
  0,   /* field[0] = static_info */
};
static const ProtobufCIntRange proto__control_plane__v1__path_segment_extensions__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 1000, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__path_segment_extensions__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.PathSegmentExtensions",
  "PathSegmentExtensions",
  "Proto__ControlPlane__V1__PathSegmentExtensions",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__PathSegmentExtensions),
  3,
  proto__control_plane__v1__path_segment_extensions__field_descriptors,
  proto__control_plane__v1__path_segment_extensions__field_indices_by_name,
  2,  proto__control_plane__v1__path_segment_extensions__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__path_segment_extensions__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__hidden_path_extension__field_descriptors[1] =
{
  {
    "is_hidden",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__HiddenPathExtension, is_hidden),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__hidden_path_extension__field_indices_by_name[] = {
  0,   /* field[0] = is_hidden */
};
static const ProtobufCIntRange proto__control_plane__v1__hidden_path_extension__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__hidden_path_extension__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.HiddenPathExtension",
  "HiddenPathExtension",
  "Proto__ControlPlane__V1__HiddenPathExtension",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__HiddenPathExtension),
  1,
  proto__control_plane__v1__hidden_path_extension__field_descriptors,
  proto__control_plane__v1__hidden_path_extension__field_indices_by_name,
  1,  proto__control_plane__v1__hidden_path_extension__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__hidden_path_extension__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__static_info_extension__geo_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension__GeoEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension__GeoEntry, value),
    &proto__control_plane__v1__geo_coordinates__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__static_info_extension__geo_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange proto__control_plane__v1__static_info_extension__geo_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__static_info_extension__geo_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.StaticInfoExtension.GeoEntry",
  "GeoEntry",
  "Proto__ControlPlane__V1__StaticInfoExtension__GeoEntry",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__StaticInfoExtension__GeoEntry),
  2,
  proto__control_plane__v1__static_info_extension__geo_entry__field_descriptors,
  proto__control_plane__v1__static_info_extension__geo_entry__field_indices_by_name,
  1,  proto__control_plane__v1__static_info_extension__geo_entry__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__static_info_extension__geo_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__static_info_extension__link_type_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension__LinkTypeEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension__LinkTypeEntry, value),
    &proto__control_plane__v1__link_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__static_info_extension__link_type_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange proto__control_plane__v1__static_info_extension__link_type_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__static_info_extension__link_type_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.StaticInfoExtension.LinkTypeEntry",
  "LinkTypeEntry",
  "Proto__ControlPlane__V1__StaticInfoExtension__LinkTypeEntry",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__StaticInfoExtension__LinkTypeEntry),
  2,
  proto__control_plane__v1__static_info_extension__link_type_entry__field_descriptors,
  proto__control_plane__v1__static_info_extension__link_type_entry__field_indices_by_name,
  1,  proto__control_plane__v1__static_info_extension__link_type_entry__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__static_info_extension__link_type_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__static_info_extension__internal_hops_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension__InternalHopsEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension__InternalHopsEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__static_info_extension__internal_hops_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange proto__control_plane__v1__static_info_extension__internal_hops_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__static_info_extension__internal_hops_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.StaticInfoExtension.InternalHopsEntry",
  "InternalHopsEntry",
  "Proto__ControlPlane__V1__StaticInfoExtension__InternalHopsEntry",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__StaticInfoExtension__InternalHopsEntry),
  2,
  proto__control_plane__v1__static_info_extension__internal_hops_entry__field_descriptors,
  proto__control_plane__v1__static_info_extension__internal_hops_entry__field_indices_by_name,
  1,  proto__control_plane__v1__static_info_extension__internal_hops_entry__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__static_info_extension__internal_hops_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__static_info_extension__field_descriptors[6] =
{
  {
    "latency",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension, latency),
    &proto__control_plane__v1__latency_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bandwidth",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension, bandwidth),
    &proto__control_plane__v1__bandwidth_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geo",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension, n_geo),
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension, geo),
    &proto__control_plane__v1__static_info_extension__geo_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "link_type",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension, n_link_type),
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension, link_type),
    &proto__control_plane__v1__static_info_extension__link_type_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "internal_hops",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension, n_internal_hops),
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension, internal_hops),
    &proto__control_plane__v1__static_info_extension__internal_hops_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "note",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__StaticInfoExtension, note),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__static_info_extension__field_indices_by_name[] = {
  1,   /* field[1] = bandwidth */
  2,   /* field[2] = geo */
  4,   /* field[4] = internal_hops */
  0,   /* field[0] = latency */
  3,   /* field[3] = link_type */
  5,   /* field[5] = note */
};
static const ProtobufCIntRange proto__control_plane__v1__static_info_extension__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__static_info_extension__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.StaticInfoExtension",
  "StaticInfoExtension",
  "Proto__ControlPlane__V1__StaticInfoExtension",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__StaticInfoExtension),
  6,
  proto__control_plane__v1__static_info_extension__field_descriptors,
  proto__control_plane__v1__static_info_extension__field_indices_by_name,
  1,  proto__control_plane__v1__static_info_extension__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__static_info_extension__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__latency_info__intra_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__LatencyInfo__IntraEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__LatencyInfo__IntraEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__latency_info__intra_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange proto__control_plane__v1__latency_info__intra_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__latency_info__intra_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.LatencyInfo.IntraEntry",
  "IntraEntry",
  "Proto__ControlPlane__V1__LatencyInfo__IntraEntry",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__LatencyInfo__IntraEntry),
  2,
  proto__control_plane__v1__latency_info__intra_entry__field_descriptors,
  proto__control_plane__v1__latency_info__intra_entry__field_indices_by_name,
  1,  proto__control_plane__v1__latency_info__intra_entry__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__latency_info__intra_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__latency_info__inter_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__LatencyInfo__InterEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__LatencyInfo__InterEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__latency_info__inter_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange proto__control_plane__v1__latency_info__inter_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__latency_info__inter_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.LatencyInfo.InterEntry",
  "InterEntry",
  "Proto__ControlPlane__V1__LatencyInfo__InterEntry",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__LatencyInfo__InterEntry),
  2,
  proto__control_plane__v1__latency_info__inter_entry__field_descriptors,
  proto__control_plane__v1__latency_info__inter_entry__field_indices_by_name,
  1,  proto__control_plane__v1__latency_info__inter_entry__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__latency_info__inter_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__latency_info__field_descriptors[2] =
{
  {
    "intra",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ControlPlane__V1__LatencyInfo, n_intra),
    offsetof(Proto__ControlPlane__V1__LatencyInfo, intra),
    &proto__control_plane__v1__latency_info__intra_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inter",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ControlPlane__V1__LatencyInfo, n_inter),
    offsetof(Proto__ControlPlane__V1__LatencyInfo, inter),
    &proto__control_plane__v1__latency_info__inter_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__latency_info__field_indices_by_name[] = {
  1,   /* field[1] = inter */
  0,   /* field[0] = intra */
};
static const ProtobufCIntRange proto__control_plane__v1__latency_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__latency_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.LatencyInfo",
  "LatencyInfo",
  "Proto__ControlPlane__V1__LatencyInfo",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__LatencyInfo),
  2,
  proto__control_plane__v1__latency_info__field_descriptors,
  proto__control_plane__v1__latency_info__field_indices_by_name,
  1,  proto__control_plane__v1__latency_info__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__latency_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__bandwidth_info__intra_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__BandwidthInfo__IntraEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__BandwidthInfo__IntraEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__bandwidth_info__intra_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange proto__control_plane__v1__bandwidth_info__intra_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__bandwidth_info__intra_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.BandwidthInfo.IntraEntry",
  "IntraEntry",
  "Proto__ControlPlane__V1__BandwidthInfo__IntraEntry",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__BandwidthInfo__IntraEntry),
  2,
  proto__control_plane__v1__bandwidth_info__intra_entry__field_descriptors,
  proto__control_plane__v1__bandwidth_info__intra_entry__field_indices_by_name,
  1,  proto__control_plane__v1__bandwidth_info__intra_entry__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__bandwidth_info__intra_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__bandwidth_info__inter_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__BandwidthInfo__InterEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__BandwidthInfo__InterEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__bandwidth_info__inter_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange proto__control_plane__v1__bandwidth_info__inter_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__bandwidth_info__inter_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.BandwidthInfo.InterEntry",
  "InterEntry",
  "Proto__ControlPlane__V1__BandwidthInfo__InterEntry",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__BandwidthInfo__InterEntry),
  2,
  proto__control_plane__v1__bandwidth_info__inter_entry__field_descriptors,
  proto__control_plane__v1__bandwidth_info__inter_entry__field_indices_by_name,
  1,  proto__control_plane__v1__bandwidth_info__inter_entry__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__bandwidth_info__inter_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__bandwidth_info__field_descriptors[2] =
{
  {
    "intra",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ControlPlane__V1__BandwidthInfo, n_intra),
    offsetof(Proto__ControlPlane__V1__BandwidthInfo, intra),
    &proto__control_plane__v1__bandwidth_info__intra_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inter",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ControlPlane__V1__BandwidthInfo, n_inter),
    offsetof(Proto__ControlPlane__V1__BandwidthInfo, inter),
    &proto__control_plane__v1__bandwidth_info__inter_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__bandwidth_info__field_indices_by_name[] = {
  1,   /* field[1] = inter */
  0,   /* field[0] = intra */
};
static const ProtobufCIntRange proto__control_plane__v1__bandwidth_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__bandwidth_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.BandwidthInfo",
  "BandwidthInfo",
  "Proto__ControlPlane__V1__BandwidthInfo",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__BandwidthInfo),
  2,
  proto__control_plane__v1__bandwidth_info__field_descriptors,
  proto__control_plane__v1__bandwidth_info__field_indices_by_name,
  1,  proto__control_plane__v1__bandwidth_info__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__bandwidth_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__geo_coordinates__field_descriptors[3] =
{
  {
    "latitude",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__GeoCoordinates, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__GeoCoordinates, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__GeoCoordinates, address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__geo_coordinates__field_indices_by_name[] = {
  2,   /* field[2] = address */
  0,   /* field[0] = latitude */
  1,   /* field[1] = longitude */
};
static const ProtobufCIntRange proto__control_plane__v1__geo_coordinates__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__geo_coordinates__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.GeoCoordinates",
  "GeoCoordinates",
  "Proto__ControlPlane__V1__GeoCoordinates",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__GeoCoordinates),
  3,
  proto__control_plane__v1__geo_coordinates__field_descriptors,
  proto__control_plane__v1__geo_coordinates__field_indices_by_name,
  1,  proto__control_plane__v1__geo_coordinates__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__geo_coordinates__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__digest_extension__digest__field_descriptors[1] =
{
  {
    "digest",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__DigestExtension__Digest, digest),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__digest_extension__digest__field_indices_by_name[] = {
  0,   /* field[0] = digest */
};
static const ProtobufCIntRange proto__control_plane__v1__digest_extension__digest__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__digest_extension__digest__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.DigestExtension.Digest",
  "Digest",
  "Proto__ControlPlane__V1__DigestExtension__Digest",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__DigestExtension__Digest),
  1,
  proto__control_plane__v1__digest_extension__digest__field_descriptors,
  proto__control_plane__v1__digest_extension__digest__field_indices_by_name,
  1,  proto__control_plane__v1__digest_extension__digest__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__digest_extension__digest__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__digest_extension__field_descriptors[1] =
{
  {
    "epic",
    1000,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__DigestExtension, epic),
    &proto__control_plane__v1__digest_extension__digest__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__digest_extension__field_indices_by_name[] = {
  0,   /* field[0] = epic */
};
static const ProtobufCIntRange proto__control_plane__v1__digest_extension__number_ranges[1 + 1] =
{
  { 1000, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__digest_extension__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.DigestExtension",
  "DigestExtension",
  "Proto__ControlPlane__V1__DigestExtension",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__DigestExtension),
  1,
  proto__control_plane__v1__digest_extension__field_descriptors,
  proto__control_plane__v1__digest_extension__field_indices_by_name,
  1,  proto__control_plane__v1__digest_extension__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__digest_extension__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__control_plane__v1__path_segment_unsigned_extensions__field_descriptors[1] =
{
  {
    "epic",
    1000,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ControlPlane__V1__PathSegmentUnsignedExtensions, epic),
    &proto__control_plane__experimental__v1__epicdetached_extension__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__control_plane__v1__path_segment_unsigned_extensions__field_indices_by_name[] = {
  0,   /* field[0] = epic */
};
static const ProtobufCIntRange proto__control_plane__v1__path_segment_unsigned_extensions__number_ranges[1 + 1] =
{
  { 1000, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__control_plane__v1__path_segment_unsigned_extensions__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.PathSegmentUnsignedExtensions",
  "PathSegmentUnsignedExtensions",
  "Proto__ControlPlane__V1__PathSegmentUnsignedExtensions",
  "proto.control_plane.v1",
  sizeof(Proto__ControlPlane__V1__PathSegmentUnsignedExtensions),
  1,
  proto__control_plane__v1__path_segment_unsigned_extensions__field_descriptors,
  proto__control_plane__v1__path_segment_unsigned_extensions__field_indices_by_name,
  1,  proto__control_plane__v1__path_segment_unsigned_extensions__number_ranges,
  (ProtobufCMessageInit) proto__control_plane__v1__path_segment_unsigned_extensions__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue proto__control_plane__v1__link_type__enum_values_by_number[4] =
{
  { "LINK_TYPE_UNSPECIFIED", "PROTO__CONTROL_PLANE__V1__LINK_TYPE__LINK_TYPE_UNSPECIFIED", 0 },
  { "LINK_TYPE_DIRECT", "PROTO__CONTROL_PLANE__V1__LINK_TYPE__LINK_TYPE_DIRECT", 1 },
  { "LINK_TYPE_MULTI_HOP", "PROTO__CONTROL_PLANE__V1__LINK_TYPE__LINK_TYPE_MULTI_HOP", 2 },
  { "LINK_TYPE_OPEN_NET", "PROTO__CONTROL_PLANE__V1__LINK_TYPE__LINK_TYPE_OPEN_NET", 3 },
};
static const ProtobufCIntRange proto__control_plane__v1__link_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex proto__control_plane__v1__link_type__enum_values_by_name[4] =
{
  { "LINK_TYPE_DIRECT", 1 },
  { "LINK_TYPE_MULTI_HOP", 2 },
  { "LINK_TYPE_OPEN_NET", 3 },
  { "LINK_TYPE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor proto__control_plane__v1__link_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "proto.control_plane.v1.LinkType",
  "LinkType",
  "Proto__ControlPlane__V1__LinkType",
  "proto.control_plane.v1",
  4,
  proto__control_plane__v1__link_type__enum_values_by_number,
  4,
  proto__control_plane__v1__link_type__enum_values_by_name,
  1,
  proto__control_plane__v1__link_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
