/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/control_plane/v1/seg_extensions.proto */

#ifndef PROTOBUF_C_proto_2fcontrol_5fplane_2fv1_2fseg_5fextensions_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fcontrol_5fplane_2fv1_2fseg_5fextensions_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "proto/control_plane/experimental/v1/seg_detached_extensions.pb-c.h"

typedef struct _Proto__ControlPlane__V1__PathSegmentExtensions Proto__ControlPlane__V1__PathSegmentExtensions;
typedef struct _Proto__ControlPlane__V1__HiddenPathExtension Proto__ControlPlane__V1__HiddenPathExtension;
typedef struct _Proto__ControlPlane__V1__StaticInfoExtension Proto__ControlPlane__V1__StaticInfoExtension;
typedef struct _Proto__ControlPlane__V1__StaticInfoExtension__GeoEntry Proto__ControlPlane__V1__StaticInfoExtension__GeoEntry;
typedef struct _Proto__ControlPlane__V1__StaticInfoExtension__LinkTypeEntry Proto__ControlPlane__V1__StaticInfoExtension__LinkTypeEntry;
typedef struct _Proto__ControlPlane__V1__StaticInfoExtension__InternalHopsEntry Proto__ControlPlane__V1__StaticInfoExtension__InternalHopsEntry;
typedef struct _Proto__ControlPlane__V1__LatencyInfo Proto__ControlPlane__V1__LatencyInfo;
typedef struct _Proto__ControlPlane__V1__LatencyInfo__IntraEntry Proto__ControlPlane__V1__LatencyInfo__IntraEntry;
typedef struct _Proto__ControlPlane__V1__LatencyInfo__InterEntry Proto__ControlPlane__V1__LatencyInfo__InterEntry;
typedef struct _Proto__ControlPlane__V1__BandwidthInfo Proto__ControlPlane__V1__BandwidthInfo;
typedef struct _Proto__ControlPlane__V1__BandwidthInfo__IntraEntry Proto__ControlPlane__V1__BandwidthInfo__IntraEntry;
typedef struct _Proto__ControlPlane__V1__BandwidthInfo__InterEntry Proto__ControlPlane__V1__BandwidthInfo__InterEntry;
typedef struct _Proto__ControlPlane__V1__GeoCoordinates Proto__ControlPlane__V1__GeoCoordinates;
typedef struct _Proto__ControlPlane__V1__DigestExtension Proto__ControlPlane__V1__DigestExtension;
typedef struct _Proto__ControlPlane__V1__DigestExtension__Digest Proto__ControlPlane__V1__DigestExtension__Digest;
typedef struct _Proto__ControlPlane__V1__PathSegmentUnsignedExtensions Proto__ControlPlane__V1__PathSegmentUnsignedExtensions;


/* --- enums --- */

typedef enum _Proto__ControlPlane__V1__LinkType {
  /*
   * Unspecified link type.
   */
  PROTO__CONTROL_PLANE__V1__LINK_TYPE__LINK_TYPE_UNSPECIFIED = 0,
  /*
   * Direct physical connection.
   */
  PROTO__CONTROL_PLANE__V1__LINK_TYPE__LINK_TYPE_DIRECT = 1,
  /*
   * Connection with local routing/switching.
   */
  PROTO__CONTROL_PLANE__V1__LINK_TYPE__LINK_TYPE_MULTI_HOP = 2,
  /*
   * Connection overlayed over publicly routed Internet.
   */
  PROTO__CONTROL_PLANE__V1__LINK_TYPE__LINK_TYPE_OPEN_NET = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO__CONTROL_PLANE__V1__LINK_TYPE)
} Proto__ControlPlane__V1__LinkType;

/* --- messages --- */

struct  _Proto__ControlPlane__V1__PathSegmentExtensions
{
  ProtobufCMessage base;
  /*
   * Optional static info extension.
   */
  Proto__ControlPlane__V1__StaticInfoExtension *static_info;
  /*
   * Optional hidden path extension.
   */
  Proto__ControlPlane__V1__HiddenPathExtension *hidden_path;
  /*
   * Optional digests of detached extensions.
   */
  Proto__ControlPlane__V1__DigestExtension *digests;
};
#define PROTO__CONTROL_PLANE__V1__PATH_SEGMENT_EXTENSIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__path_segment_extensions__descriptor) \
    , NULL, NULL, NULL }


struct  _Proto__ControlPlane__V1__HiddenPathExtension
{
  ProtobufCMessage base;
  /*
   * Indicate if this is a hidden path.
   */
  protobuf_c_boolean is_hidden;
};
#define PROTO__CONTROL_PLANE__V1__HIDDEN_PATH_EXTENSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__hidden_path_extension__descriptor) \
    , 0 }


struct  _Proto__ControlPlane__V1__StaticInfoExtension__GeoEntry
{
  ProtobufCMessage base;
  uint64_t key;
  Proto__ControlPlane__V1__GeoCoordinates *value;
};
#define PROTO__CONTROL_PLANE__V1__STATIC_INFO_EXTENSION__GEO_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__static_info_extension__geo_entry__descriptor) \
    , 0, NULL }


struct  _Proto__ControlPlane__V1__StaticInfoExtension__LinkTypeEntry
{
  ProtobufCMessage base;
  uint64_t key;
  Proto__ControlPlane__V1__LinkType value;
};
#define PROTO__CONTROL_PLANE__V1__STATIC_INFO_EXTENSION__LINK_TYPE_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__static_info_extension__link_type_entry__descriptor) \
    , 0, PROTO__CONTROL_PLANE__V1__LINK_TYPE__LINK_TYPE_UNSPECIFIED }


struct  _Proto__ControlPlane__V1__StaticInfoExtension__InternalHopsEntry
{
  ProtobufCMessage base;
  uint64_t key;
  uint32_t value;
};
#define PROTO__CONTROL_PLANE__V1__STATIC_INFO_EXTENSION__INTERNAL_HOPS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__static_info_extension__internal_hops_entry__descriptor) \
    , 0, 0 }


struct  _Proto__ControlPlane__V1__StaticInfoExtension
{
  ProtobufCMessage base;
  /*
   * Approximate, lower-bound latency for paths based on this ASEntry.
   */
  Proto__ControlPlane__V1__LatencyInfo *latency;
  /*
   * Approximate, maximum bandwidth for paths based on this ASEntry.
   */
  Proto__ControlPlane__V1__BandwidthInfo *bandwidth;
  /*
   * Geographical coordinates describing the location of the routers for
   * relevant interfaces of this AS. The key is the interface identifier.
   */
  size_t n_geo;
  Proto__ControlPlane__V1__StaticInfoExtension__GeoEntry **geo;
  /*
   * Description of the underlying network for the inter-AS links, for the
   * relevant interfaces of this AS. The key is the interface identifier.
   */
  size_t n_link_type;
  Proto__ControlPlane__V1__StaticInfoExtension__LinkTypeEntry **link_type;
  /*
   * Number of AS internal hops between the construction-egress and the
   * relevant other interfaces. These are:
   * - construction-ingress interface (if any)
   * - sibling child interfaces,
   * - core interfaces, at start or end of a segment
   * - peer interfaces
   * The key is the interface identifier of the other interface.
   */
  size_t n_internal_hops;
  Proto__ControlPlane__V1__StaticInfoExtension__InternalHopsEntry **internal_hops;
  /*
   * Generic note
   */
  char *note;
};
#define PROTO__CONTROL_PLANE__V1__STATIC_INFO_EXTENSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__static_info_extension__descriptor) \
    , NULL, NULL, 0,NULL, 0,NULL, 0,NULL, (char *)protobuf_c_empty_string }


struct  _Proto__ControlPlane__V1__LatencyInfo__IntraEntry
{
  ProtobufCMessage base;
  uint64_t key;
  uint32_t value;
};
#define PROTO__CONTROL_PLANE__V1__LATENCY_INFO__INTRA_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__latency_info__intra_entry__descriptor) \
    , 0, 0 }


struct  _Proto__ControlPlane__V1__LatencyInfo__InterEntry
{
  ProtobufCMessage base;
  uint64_t key;
  uint32_t value;
};
#define PROTO__CONTROL_PLANE__V1__LATENCY_INFO__INTER_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__latency_info__inter_entry__descriptor) \
    , 0, 0 }


/*
 * LatencyInfo specifies approximate lower-bound latency values.
 * The separate intra and inter AS latency information allows to reconstruct
 * latency values for all paths (cross-over, shortcut, peering) based on this
 * ASEntry.
 * All values are in microseconds.
 */
struct  _Proto__ControlPlane__V1__LatencyInfo
{
  ProtobufCMessage base;
  /*
   * Latency between construction-egress interface and the relevant other
   * interfaces. These are:
   * - construction-ingress interface (if any)
   * - sibling child interfaces,
   * - core interfaces, at start or end of a segment
   * - peer interfaces
   * The key is the interface identifier of the other interface.
   */
  size_t n_intra;
  Proto__ControlPlane__V1__LatencyInfo__IntraEntry **intra;
  /*
   * Latency between the local interface and the interface in the neighbor AS
   * for the relevant links. These are:
   * - link at construction-egress interface (if any)
   * - peer links
   * The key is the interface identifier of the local interface associated
   * with the link.
   */
  size_t n_inter;
  Proto__ControlPlane__V1__LatencyInfo__InterEntry **inter;
};
#define PROTO__CONTROL_PLANE__V1__LATENCY_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__latency_info__descriptor) \
    , 0,NULL, 0,NULL }


struct  _Proto__ControlPlane__V1__BandwidthInfo__IntraEntry
{
  ProtobufCMessage base;
  uint64_t key;
  uint64_t value;
};
#define PROTO__CONTROL_PLANE__V1__BANDWIDTH_INFO__INTRA_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__bandwidth_info__intra_entry__descriptor) \
    , 0, 0 }


struct  _Proto__ControlPlane__V1__BandwidthInfo__InterEntry
{
  ProtobufCMessage base;
  uint64_t key;
  uint64_t value;
};
#define PROTO__CONTROL_PLANE__V1__BANDWIDTH_INFO__INTER_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__bandwidth_info__inter_entry__descriptor) \
    , 0, 0 }


/*
 * BandwidthInfo specifies approximate maximum link bandwidth.
 * The separate intra and inter AS bandwidth information allows to reconstruct
 * bandwidth values for all paths (cross-over, shortcut, peering) based on this
 * ASEntry.
 * All values are in Kbit/s.
 */
struct  _Proto__ControlPlane__V1__BandwidthInfo
{
  ProtobufCMessage base;
  /*
   * Bandwidth between construction-egress interface and the relevant other
   * interfaces. These are:
   * - construction-ingress interface (if any)
   * - sibling child interfaces,
   * - core interfaces, if this is the start of a segment, or the end of a core segment
   * - peer interfaces
   * The key is the interface identifier of the other interface.
   */
  size_t n_intra;
  Proto__ControlPlane__V1__BandwidthInfo__IntraEntry **intra;
  /*
   * Bandwidth between the local interface and the interface in the neighbor AS
   * for the relevant links. These are:
   * - link at construction-egress interface (if any)
   * - peer links
   * The key is the interface identifier of the local interface associated
   * with the link.
   */
  size_t n_inter;
  Proto__ControlPlane__V1__BandwidthInfo__InterEntry **inter;
};
#define PROTO__CONTROL_PLANE__V1__BANDWIDTH_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__bandwidth_info__descriptor) \
    , 0,NULL, 0,NULL }


struct  _Proto__ControlPlane__V1__GeoCoordinates
{
  ProtobufCMessage base;
  /*
   * Latitude of the geographic coordinate, in the WGS 84 datum.
   */
  float latitude;
  /*
   * Longitude of the geographic coordinate, in the WGS 84 datum.
   */
  float longitude;
  /*
   * Civic address of the location.
   */
  char *address;
};
#define PROTO__CONTROL_PLANE__V1__GEO_COORDINATES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__geo_coordinates__descriptor) \
    , 0, 0, (char *)protobuf_c_empty_string }


struct  _Proto__ControlPlane__V1__DigestExtension__Digest
{
  ProtobufCMessage base;
  /*
   * Raw digest of the metadata.
   */
  ProtobufCBinaryData digest;
};
#define PROTO__CONTROL_PLANE__V1__DIGEST_EXTENSION__DIGEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__digest_extension__digest__descriptor) \
    , {0,NULL} }


struct  _Proto__ControlPlane__V1__DigestExtension
{
  ProtobufCMessage base;
  /*
   * The digest of the detached EPIC extension. The hash input is defined as follows:
   * input = totalLen ||
   *         epic.Detached.AuthHopEntry ||
   *         epic.Detached.AuthPeerEntries[0] ||
   *         epic.Detached.AuthPeerEntries[1] ||
   *         ...
   *         epic.Detached.AuthPeerEntries[n-1]
   * Here, 'n' denotes the number of peer entries.
   * 'totalLen' is equal to (n+1), and therefore encodes the
   * total number of authenticators used in the hash.
   */
  Proto__ControlPlane__V1__DigestExtension__Digest *epic;
};
#define PROTO__CONTROL_PLANE__V1__DIGEST_EXTENSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__digest_extension__descriptor) \
    , NULL }


struct  _Proto__ControlPlane__V1__PathSegmentUnsignedExtensions
{
  ProtobufCMessage base;
  /*
   * Optional EPIC extension.
   */
  Proto__ControlPlane__Experimental__V1__EPICDetachedExtension *epic;
};
#define PROTO__CONTROL_PLANE__V1__PATH_SEGMENT_UNSIGNED_EXTENSIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__control_plane__v1__path_segment_unsigned_extensions__descriptor) \
    , NULL }


/* Proto__ControlPlane__V1__PathSegmentExtensions methods */
void   proto__control_plane__v1__path_segment_extensions__init
                     (Proto__ControlPlane__V1__PathSegmentExtensions         *message);
size_t proto__control_plane__v1__path_segment_extensions__get_packed_size
                     (const Proto__ControlPlane__V1__PathSegmentExtensions   *message);
size_t proto__control_plane__v1__path_segment_extensions__pack
                     (const Proto__ControlPlane__V1__PathSegmentExtensions   *message,
                      uint8_t             *out);
size_t proto__control_plane__v1__path_segment_extensions__pack_to_buffer
                     (const Proto__ControlPlane__V1__PathSegmentExtensions   *message,
                      ProtobufCBuffer     *buffer);
Proto__ControlPlane__V1__PathSegmentExtensions *
       proto__control_plane__v1__path_segment_extensions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__control_plane__v1__path_segment_extensions__free_unpacked
                     (Proto__ControlPlane__V1__PathSegmentExtensions *message,
                      ProtobufCAllocator *allocator);
/* Proto__ControlPlane__V1__HiddenPathExtension methods */
void   proto__control_plane__v1__hidden_path_extension__init
                     (Proto__ControlPlane__V1__HiddenPathExtension         *message);
size_t proto__control_plane__v1__hidden_path_extension__get_packed_size
                     (const Proto__ControlPlane__V1__HiddenPathExtension   *message);
size_t proto__control_plane__v1__hidden_path_extension__pack
                     (const Proto__ControlPlane__V1__HiddenPathExtension   *message,
                      uint8_t             *out);
size_t proto__control_plane__v1__hidden_path_extension__pack_to_buffer
                     (const Proto__ControlPlane__V1__HiddenPathExtension   *message,
                      ProtobufCBuffer     *buffer);
Proto__ControlPlane__V1__HiddenPathExtension *
       proto__control_plane__v1__hidden_path_extension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__control_plane__v1__hidden_path_extension__free_unpacked
                     (Proto__ControlPlane__V1__HiddenPathExtension *message,
                      ProtobufCAllocator *allocator);
/* Proto__ControlPlane__V1__StaticInfoExtension__GeoEntry methods */
void   proto__control_plane__v1__static_info_extension__geo_entry__init
                     (Proto__ControlPlane__V1__StaticInfoExtension__GeoEntry         *message);
/* Proto__ControlPlane__V1__StaticInfoExtension__LinkTypeEntry methods */
void   proto__control_plane__v1__static_info_extension__link_type_entry__init
                     (Proto__ControlPlane__V1__StaticInfoExtension__LinkTypeEntry         *message);
/* Proto__ControlPlane__V1__StaticInfoExtension__InternalHopsEntry methods */
void   proto__control_plane__v1__static_info_extension__internal_hops_entry__init
                     (Proto__ControlPlane__V1__StaticInfoExtension__InternalHopsEntry         *message);
/* Proto__ControlPlane__V1__StaticInfoExtension methods */
void   proto__control_plane__v1__static_info_extension__init
                     (Proto__ControlPlane__V1__StaticInfoExtension         *message);
size_t proto__control_plane__v1__static_info_extension__get_packed_size
                     (const Proto__ControlPlane__V1__StaticInfoExtension   *message);
size_t proto__control_plane__v1__static_info_extension__pack
                     (const Proto__ControlPlane__V1__StaticInfoExtension   *message,
                      uint8_t             *out);
size_t proto__control_plane__v1__static_info_extension__pack_to_buffer
                     (const Proto__ControlPlane__V1__StaticInfoExtension   *message,
                      ProtobufCBuffer     *buffer);
Proto__ControlPlane__V1__StaticInfoExtension *
       proto__control_plane__v1__static_info_extension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__control_plane__v1__static_info_extension__free_unpacked
                     (Proto__ControlPlane__V1__StaticInfoExtension *message,
                      ProtobufCAllocator *allocator);
/* Proto__ControlPlane__V1__LatencyInfo__IntraEntry methods */
void   proto__control_plane__v1__latency_info__intra_entry__init
                     (Proto__ControlPlane__V1__LatencyInfo__IntraEntry         *message);
/* Proto__ControlPlane__V1__LatencyInfo__InterEntry methods */
void   proto__control_plane__v1__latency_info__inter_entry__init
                     (Proto__ControlPlane__V1__LatencyInfo__InterEntry         *message);
/* Proto__ControlPlane__V1__LatencyInfo methods */
void   proto__control_plane__v1__latency_info__init
                     (Proto__ControlPlane__V1__LatencyInfo         *message);
size_t proto__control_plane__v1__latency_info__get_packed_size
                     (const Proto__ControlPlane__V1__LatencyInfo   *message);
size_t proto__control_plane__v1__latency_info__pack
                     (const Proto__ControlPlane__V1__LatencyInfo   *message,
                      uint8_t             *out);
size_t proto__control_plane__v1__latency_info__pack_to_buffer
                     (const Proto__ControlPlane__V1__LatencyInfo   *message,
                      ProtobufCBuffer     *buffer);
Proto__ControlPlane__V1__LatencyInfo *
       proto__control_plane__v1__latency_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__control_plane__v1__latency_info__free_unpacked
                     (Proto__ControlPlane__V1__LatencyInfo *message,
                      ProtobufCAllocator *allocator);
/* Proto__ControlPlane__V1__BandwidthInfo__IntraEntry methods */
void   proto__control_plane__v1__bandwidth_info__intra_entry__init
                     (Proto__ControlPlane__V1__BandwidthInfo__IntraEntry         *message);
/* Proto__ControlPlane__V1__BandwidthInfo__InterEntry methods */
void   proto__control_plane__v1__bandwidth_info__inter_entry__init
                     (Proto__ControlPlane__V1__BandwidthInfo__InterEntry         *message);
/* Proto__ControlPlane__V1__BandwidthInfo methods */
void   proto__control_plane__v1__bandwidth_info__init
                     (Proto__ControlPlane__V1__BandwidthInfo         *message);
size_t proto__control_plane__v1__bandwidth_info__get_packed_size
                     (const Proto__ControlPlane__V1__BandwidthInfo   *message);
size_t proto__control_plane__v1__bandwidth_info__pack
                     (const Proto__ControlPlane__V1__BandwidthInfo   *message,
                      uint8_t             *out);
size_t proto__control_plane__v1__bandwidth_info__pack_to_buffer
                     (const Proto__ControlPlane__V1__BandwidthInfo   *message,
                      ProtobufCBuffer     *buffer);
Proto__ControlPlane__V1__BandwidthInfo *
       proto__control_plane__v1__bandwidth_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__control_plane__v1__bandwidth_info__free_unpacked
                     (Proto__ControlPlane__V1__BandwidthInfo *message,
                      ProtobufCAllocator *allocator);
/* Proto__ControlPlane__V1__GeoCoordinates methods */
void   proto__control_plane__v1__geo_coordinates__init
                     (Proto__ControlPlane__V1__GeoCoordinates         *message);
size_t proto__control_plane__v1__geo_coordinates__get_packed_size
                     (const Proto__ControlPlane__V1__GeoCoordinates   *message);
size_t proto__control_plane__v1__geo_coordinates__pack
                     (const Proto__ControlPlane__V1__GeoCoordinates   *message,
                      uint8_t             *out);
size_t proto__control_plane__v1__geo_coordinates__pack_to_buffer
                     (const Proto__ControlPlane__V1__GeoCoordinates   *message,
                      ProtobufCBuffer     *buffer);
Proto__ControlPlane__V1__GeoCoordinates *
       proto__control_plane__v1__geo_coordinates__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__control_plane__v1__geo_coordinates__free_unpacked
                     (Proto__ControlPlane__V1__GeoCoordinates *message,
                      ProtobufCAllocator *allocator);
/* Proto__ControlPlane__V1__DigestExtension__Digest methods */
void   proto__control_plane__v1__digest_extension__digest__init
                     (Proto__ControlPlane__V1__DigestExtension__Digest         *message);
/* Proto__ControlPlane__V1__DigestExtension methods */
void   proto__control_plane__v1__digest_extension__init
                     (Proto__ControlPlane__V1__DigestExtension         *message);
size_t proto__control_plane__v1__digest_extension__get_packed_size
                     (const Proto__ControlPlane__V1__DigestExtension   *message);
size_t proto__control_plane__v1__digest_extension__pack
                     (const Proto__ControlPlane__V1__DigestExtension   *message,
                      uint8_t             *out);
size_t proto__control_plane__v1__digest_extension__pack_to_buffer
                     (const Proto__ControlPlane__V1__DigestExtension   *message,
                      ProtobufCBuffer     *buffer);
Proto__ControlPlane__V1__DigestExtension *
       proto__control_plane__v1__digest_extension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__control_plane__v1__digest_extension__free_unpacked
                     (Proto__ControlPlane__V1__DigestExtension *message,
                      ProtobufCAllocator *allocator);
/* Proto__ControlPlane__V1__PathSegmentUnsignedExtensions methods */
void   proto__control_plane__v1__path_segment_unsigned_extensions__init
                     (Proto__ControlPlane__V1__PathSegmentUnsignedExtensions         *message);
size_t proto__control_plane__v1__path_segment_unsigned_extensions__get_packed_size
                     (const Proto__ControlPlane__V1__PathSegmentUnsignedExtensions   *message);
size_t proto__control_plane__v1__path_segment_unsigned_extensions__pack
                     (const Proto__ControlPlane__V1__PathSegmentUnsignedExtensions   *message,
                      uint8_t             *out);
size_t proto__control_plane__v1__path_segment_unsigned_extensions__pack_to_buffer
                     (const Proto__ControlPlane__V1__PathSegmentUnsignedExtensions   *message,
                      ProtobufCBuffer     *buffer);
Proto__ControlPlane__V1__PathSegmentUnsignedExtensions *
       proto__control_plane__v1__path_segment_unsigned_extensions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__control_plane__v1__path_segment_unsigned_extensions__free_unpacked
                     (Proto__ControlPlane__V1__PathSegmentUnsignedExtensions *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Proto__ControlPlane__V1__PathSegmentExtensions_Closure)
                 (const Proto__ControlPlane__V1__PathSegmentExtensions *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__HiddenPathExtension_Closure)
                 (const Proto__ControlPlane__V1__HiddenPathExtension *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__StaticInfoExtension__GeoEntry_Closure)
                 (const Proto__ControlPlane__V1__StaticInfoExtension__GeoEntry *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__StaticInfoExtension__LinkTypeEntry_Closure)
                 (const Proto__ControlPlane__V1__StaticInfoExtension__LinkTypeEntry *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__StaticInfoExtension__InternalHopsEntry_Closure)
                 (const Proto__ControlPlane__V1__StaticInfoExtension__InternalHopsEntry *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__StaticInfoExtension_Closure)
                 (const Proto__ControlPlane__V1__StaticInfoExtension *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__LatencyInfo__IntraEntry_Closure)
                 (const Proto__ControlPlane__V1__LatencyInfo__IntraEntry *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__LatencyInfo__InterEntry_Closure)
                 (const Proto__ControlPlane__V1__LatencyInfo__InterEntry *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__LatencyInfo_Closure)
                 (const Proto__ControlPlane__V1__LatencyInfo *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__BandwidthInfo__IntraEntry_Closure)
                 (const Proto__ControlPlane__V1__BandwidthInfo__IntraEntry *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__BandwidthInfo__InterEntry_Closure)
                 (const Proto__ControlPlane__V1__BandwidthInfo__InterEntry *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__BandwidthInfo_Closure)
                 (const Proto__ControlPlane__V1__BandwidthInfo *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__GeoCoordinates_Closure)
                 (const Proto__ControlPlane__V1__GeoCoordinates *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__DigestExtension__Digest_Closure)
                 (const Proto__ControlPlane__V1__DigestExtension__Digest *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__DigestExtension_Closure)
                 (const Proto__ControlPlane__V1__DigestExtension *message,
                  void *closure_data);
typedef void (*Proto__ControlPlane__V1__PathSegmentUnsignedExtensions_Closure)
                 (const Proto__ControlPlane__V1__PathSegmentUnsignedExtensions *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    proto__control_plane__v1__link_type__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__path_segment_extensions__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__hidden_path_extension__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__static_info_extension__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__static_info_extension__geo_entry__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__static_info_extension__link_type_entry__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__static_info_extension__internal_hops_entry__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__latency_info__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__latency_info__intra_entry__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__latency_info__inter_entry__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__bandwidth_info__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__bandwidth_info__intra_entry__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__bandwidth_info__inter_entry__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__geo_coordinates__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__digest_extension__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__digest_extension__digest__descriptor;
extern const ProtobufCMessageDescriptor proto__control_plane__v1__path_segment_unsigned_extensions__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fcontrol_5fplane_2fv1_2fseg_5fextensions_2eproto__INCLUDED */
