# Copied from https://github.com/nghttp2/nghttp2.git and modified

include(CheckCCompilerFlag)
include(CheckLinkerFlag)

function(extract_valid_c_compiler_flags varname)
    set(valid_flags)
    foreach (flag IN LISTS ARGN)
        string(REGEX REPLACE "[^a-zA-Z0-9_]+" "_" flag_var ${flag})
        set(flag_var "C_COMPILER_FLAG_${flag_var}")
        check_c_compiler_flag("${flag}" "${flag_var}")
        if (${flag_var})
            list(APPEND valid_flags "${flag}")
        endif ()
    endforeach ()
    set(${varname} "${valid_flags}" PARENT_SCOPE)
endfunction()

function(extract_valid_c_linker_flags varname)
    set(valid_flags)
    foreach (flag IN LISTS ARGN)
        string(REGEX REPLACE "[^a-zA-Z0-9_]+" "_" flag_var ${flag})
        set(flag_var "C_LINKER_FLAG_${flag_var}")
        check_linker_flag(C "${flag}" "${flag_var}")
        if (${flag_var})
            list(APPEND valid_flags "${flag}")
        endif ()
    endforeach ()
    set(${varname} "${valid_flags}" PARENT_SCOPE)
endfunction()